---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-user-100
  name: demo-user-100
spec:
  ports:
  - port: 80
    targetPort: 8088
    name: superset
  - port: 8290
    name: divolte
  selector:
    run: demo-user-100
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-user-100
  name: demo-user-100
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-user-100
  template:
    metadata:
      labels:
        run: demo-user-100
    spec:
      containers:
      - image: tylerfowler/superset:0.20.1
        imagePullPolicy: Always
        name: demo-user-100-superset
        ports:
        - containerPort: 8088
        volumeMounts:
          - name: demo-user-100-superset
            mountPath: /superset/
        readinessProbe:
          httpGet:
            path: /login/
            port: 8088
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - image: gcr.io/intentaware-1253/ia-divolte:0.6.0-0.2.3
        imagePullPolicy: Always
        name: demo-user-100-divolte
        ports:
        - containerPort: 8290
        env:
        - name: DIVOLTE_KAFKA_BROKER_LIST
          value : "demo-kafka-hs.default.svc.cluster.local:9093"
        - name: DIVOLTE_KAFKA_CLIENT_ID
          value : divolte-user-100
        - name: DIVOLTE_KAFKA_TOPIC
          value : kafka-user-100
        readinessProbe:
          httpGet:
            path: /
            port: 8290
          initialDelaySeconds: 5
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        - name: demo-user-100-superset
          persistentVolumeClaim:
            claimName: demo-user-100-superset
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-user-100-superset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
