---
apiVersion: v1
kind: Service
metadata:
  name: prod-dbroker-hs
  labels:
    app: prod-dbroker
spec:
  ports:
  - port: 8082
    name: coordinator
  selector:
    app: prod-dbroker
  clusterIP: None
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prod-dbroker-pdb
spec:
  selector:
    matchLabels:
      app: prod-dbroker
  maxUnavailable: 1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: prod-dbroker
spec:
  serviceName: prod-dbroker-hs
  replicas: 2
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod-dbroker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - prod-dbroker
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1
               podAffinityTerm:
                 labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                        - zk
                 topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
      - name: prod-dbroker
        imagePullPolicy: Always
        image: gcr.io/intentaware-1253/ia-druid-base:0.10.1-0.1
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 8082
          name: coordinator
        command:
        - sh
        - -c
        - "exec java \
          -server \
          -Xmx1g \
          -Duser.timezone=UTC \
          -Dfile.encoding=UTF-8 \
          -Ddruid.zk.service.host=prod-zk-cs.default.svc.cluster.local:2181 \
          -Ddruid.zk.paths.base=/druid/prod \
          -Ddruid.discovery.curator.path=/prod/discovery \
          -Ddruid.computation.buffer.size=67108864 \
          -Ddruid.broker.cache.sizeInBytes=33554432 \
          -cp /usr/local/druid/lib/* \
          io.druid.cli.Main server broker "
        readinessProbe:
          exec:
           command:
            - sh
            - -c
            - "exec curl -X GET http://localhost:8082/status "
